
solver:
  type: "conjugate_gradient"  # Options: direct, fst, lu, cholesky, low_rank, jacobi, conjugate_gradient, multigrid, graph, priority_queue
  preconditioner: "jacobi"    # Options: none, jacobi, incomplete_cholesky
  tolerance: 1e-8
  max_iterations: 1000

grid:
  type: "uniform"              # Options: uniform, non-uniform
  Nx: 20
  Ny: 20

problem:
  use_sparse: true